CircleCI-Public/circleci-server-monitoring-reference

- .circleci/config.yml
- .github/CODEOWNERS
- .github/PULL_REQUEST_TEMPLATE.md
- .gitignore
- LICENSE
- README.md
Jira: https://circleci.atlassian.net/browse/ONPREM-1861
> Initialize repo

- renovate.json5
> Set up Renovate

- templates/prometheus-operator/clusterrolebinding.yaml
- templates/prometheus-operator/deployment.yaml
- templates/prometheus/clusterrole.yaml
- templates/prometheus/clusterrolebinding.yaml
- templates/prometheus/prometheus.yaml
- templates/prometheus/service.yaml
- templates/prometheus/serviceaccount.yaml
- templates/prometheus/servicemonitor.yaml
- tests/prometheus/prometheus_test.yaml
- tests/prometheus/servicemonitor_test.yaml
- values.yaml
https://circleci.atlassian.net/browse/ONPREM-1862
---
This PR is a followup to PR #2. Here, we set up Prometheus and target the existing Telegraf deployment in server, which is the default metrics collector for all server components.
---
---
I added applicable Helm unit tests. In addition, I manually tested this against a fresh server install. In the screenshot below, we can see that Telegraf is being correctly targeted:
---
I'll add documentation along with a Helm values table in a followup PR.
> [ONPREM-1862] Set up Prometheus

- README.md
- README.md.gotmpl
> Fix README

- .circleci/config.yml
- Chart.lock
- Chart.yaml
- README.md
- README.md.gotmpl
- do
- templates/_helpers.tpl
- templates/grafana/dashboards.yaml
- templates/grafana/datasource.yaml
- templates/grafana/grafana.yaml
- templates/grafana/pvc.yaml
- templates/grafana/secret.yaml
- tests/grafana/dashboards_test.yaml
- tests/grafana/datasource_test.yaml
- tests/grafana/grafana_test.yaml
- tests/grafana/pvc_test.yaml
- tests/grafana/secret_test.yaml
- tests/kubeconform/global-image-pull-secrets-values.yaml
- tests/kubeconform/grafana-pvc-values.yaml
- values.yaml
https://circleci.atlassian.net/browse/ONPREM-1863
---
---
---
The unit tests and smoke tests have all been updated to check the Grafana deployment and resources. I also performed manual testing to verify that the sample dashboard is populated accordingly:
---
I will add additional installation steps in the README for Grafana in a followup PR.
> [ONPREM-1863] Set up Grafana

- README.md
- README.md.gotmpl
- templates/grafana/grafana.yaml
- tests/grafana/grafana_test.yaml
- tests/kubeconform/grafana-ingress-values.yaml
- tests/kubeconform/grafana-svc-values.yaml
- values.yaml
The previous values didn't work
---
---
---
---
> [1865] Add options to expose Grafana externally

- templates/prometheus/clusterrolebinding.yaml
Broke this in PR #14
---
---
---
---
> Fix ClusterRoleBinding for Prometheus

- .circleci/config.yml
- .helmignore
- do
---
Start packaging and signing the Helm chart. In a followup PR, I'll be publishing it to the [PackageCloud repository](https://packagecloud.io/circleci/server-monitoring-stack).
---
---
The smoke tests have been updated to exercise the packaged chart by installing from the tarball.
---
I will update the docs once we start publishing the chart to PackageCloud.
> [ONPREM-2020] Package Helm chart

- .circleci/config.yml
- Chart.yaml
- README.md
- do
https://circleci.atlassian.net/browse/ONPREM-2020
---
---
---
Performed some manual testing: https://app.circleci.com/pipelines/github/CircleCI-Public/circleci-server-monitoring-reference/227/workflows/8cbba7cc-efbf-47b5-a9f0-9807ede35c74/jobs/894
---
I will update the README with instructions on how to install the chart from Packagecloud, as well as add docs on the release process for developers
> [ONPREM-2020] Push Helm chart to Packagecloud repo

- .circleci/config.yml
- Chart.yaml
- README.md
- README.md.gotmpl
- do
> [ONPREM-2020] Update docs on Helm repo and shorten chart name

- .circleci/config.yml
> [ONPREM-2020] Create releases in GitHub

- .circleci/config.yml
- README.md
- README.md.gotmpl
> Fix create-release job

- .circleci/config.yml
It requires a notes option, or else it'll hang indefinitely
---
---
---
---
> Fix gh release create command

- .circleci/config.yml
It's required for the ./do version command
---
---
---
---
> Install Helm in create-release job

- Chart.yaml
- README.md
- templates/grafana/grafana.yaml
> [ONPREM-1865] Set port name for Grafana

- .circleci/config.yml
- README.md
- dashboards/circleci-api-usage-dashboard.json
- do
- templates/grafana/dashboards.yaml
- tests/grafana/dashboards_test.yaml
- values.yaml
This is a bit more wieldy. This also enables us to add linting for the dashboards.
---
---
---
---
> [ONPREM-1864] Load default dashboards from JSON files

- README.md
- README.md.gotmpl
> Add docs on adding and modifying dashboards

- .circleci/config.yml
- .helmignore
- README.md
- README.md.gotmpl
- dashboards/.lint
- do
- scripts/validate_dashboards.sh
https://circleci.atlassian.net/browse/ONPREM-2094
---
---
---
---
> [ONPREM-2094] Add custom dashboard linting and validation

- README.md
- README.md.gotmpl
Update the docs with a support + responsibility disclaimer from Legal.
---
Adding a disclaimer from our legal team regrading the responsibility CircleCI has for this reference repository.
> add support disclaimer to README

- .circleci/config.yml
- Chart.yaml
- README.md
- values.yaml
> Work around bug in Grafana subchart

- .circleci/config.yml
- Chart.yaml
- README.md
- values.yaml
---
Cutting a release mainly to get a patch in Grafana for a high severity CVE.
---
---
---
> Prepare 0.1.0-alpha.4 release

- .circleci/config.yml
- README.md
- README.md.gotmpl
- templates/tempo/tempomonolithic.yaml
- tests/kubeconform/pvc-values.yaml
- tests/tempo/tempomonolithic_test.yaml
- values.yaml
https://circleci.atlassian.net/browse/ONPREM-2157
---
Bumps tempo-operator and exposes some additional storage class and security options per https://github.com/grafana/tempo-operator/issues/1231
---
---
---
> [ONPREM-2157] Update tempo-operator to 0.17 with storage class and security context

- Chart.yaml
- README.md
> Prepare 0.1.0-alpha.7 release
